/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER MDY2231_P7 
IDENTIFIED BY "MDY2231.practica_7"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

ALTER USER MDY2231_P7 QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO MDY2231_P7;
GRANT "RESOURCE" TO MDY2231_P7;

ALTER USER MDY2231_P7 DEFAULT ROLE "RESOURCE";