/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER MDY2231_P2 
IDENTIFIED BY "MDY2231.practica_2"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

ALTER USER MDY2231_P2 QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO MDY2231_P2;
GRANT "RESOURCE" TO MDY2231_P2;

ALTER USER MDY2231_P2 DEFAULT ROLE "RESOURCE";