/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER MDY2231_P1 
IDENTIFIED BY "MDY2231.practica_1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

ALTER USER MDY2231_P1 QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO MDY2231_P1;
GRANT "RESOURCE" TO MDY2231_P1;

ALTER USER MDY2231_P1 DEFAULT ROLE "RESOURCE";