/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER MDY2231_P5 
IDENTIFIED BY "MDY2231.practica_5"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

ALTER USER MDY2231_P5 QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO MDY2231_P5;
GRANT "RESOURCE" TO MDY2231_P5;

ALTER USER MDY2231_P5 DEFAULT ROLE "RESOURCE";